export const arrayProduct = [
  {
    id: "vinyl01",
    src: "https://via.placeholder.com/50",
    alt: "",
    title: "vinyl",
    description: "stari-noses",
    notesLabel: "Special Size - Add Ons / Notes",
    styles: "",
  },
  {
    id: "engineeredwood02",
    src: "https://via.placeholder.com/50",
    alt: "",
    title: "engineered wood",
    description: "stari-noses",
    notesLabel: "Wood Thickness / Notes",
    styles: "",
  },
  {
    id: "mouldings03",
    src: "https://via.placeholder.com/50",
    alt: "",
    title: "mouldings",
    description: "",
    notesLabel: "Special Size / Notes",
    styles: "",
  },
  {
    id: "whiteriser03",
    src: "https://via.placeholder.com/50",
    alt: "",
    title: "whiteriser",
    description: "",
    notesLabel: "Special Size / Notes",
    styles: "",
  },
];
